export { peripheryApi, wsManager, getCachedSnapshot, setCachedSnapshot, computeRendering } from './client'

// Re-export all types explicitly
export type {
  Document,
  SearchResult,
  GraphNode,
  GraphEdge,
  LegacyOntologySnapshot,
  EntityNode,
  Relationship,
  DetectedCluster,
  Trajectory,
  Anomaly,
  RelationalGradient,
  EmergingStructure,
  RenderingMetadata,
  OntologySnapshot,
  QueryOptions,
  AnalyticalQueryResponse,
  ParsedIntent,
  Finding,
  EntityResult,
  RelationshipResult,
  ClusterResult,
  TrajectoryResult,
  AnomalyResult,
  EntityDetail,
  ConfidenceExplanation,
  ConfidenceFactor,
  ClusterMembership,
  EntityRelationship,
  TemporalDataPoint,
  SourceDocument,
  ClusterDetail,
  ClusterTimelineEvent,
  PipelineStats,
  PipelineStage,
  EmbeddingStats,
  HealthStatus,
  CriticMonitoring,
  CriticExplanation,
  CriticScoreTrend,
  SnapshotDelta,
  QueryUpdate,
  LegibilityTier,
  NodeRenderState,
  QueryHistoryEntry,
  SnapshotFilters,
  ConnectionStatus,
  SourceCategory,
  FeedEntry,
  ViewMode,
  SelectedElement,
} from './types'
