export {
  peripheryApi,
  wsManager,
  getCachedSnapshot,
  setCachedSnapshot,
  computeRendering,
  subscribeToQuery,
} from './client'
export type { CommandResponse, CommandStatusEntry, CommandStatusMap } from './client'
export { PeripheryWebSocket } from './websocket'
export type { WSMessage, MessageType } from './websocket'

// Re-export all types explicitly
export type {
  Document,
  SearchResult,
  GraphNode,
  GraphEdge,
  LegacyOntologySnapshot,
  EntityNode,
  Relationship,
  DetectedCluster,
  Trajectory,
  Anomaly,
  RelationalGradient,
  EmergingStructure,
  RenderingMetadata,
  OntologySnapshot,
  QueryOptions,
  AnalyticalQueryResponse,
  ParsedIntent,
  Finding,
  EntityResult,
  RelationshipResult,
  ClusterResult,
  TrajectoryResult,
  AnomalyResult,
  EntityDetail,
  ConfidenceExplanation,
  ConfidenceFactor,
  ClusterMembership,
  EntityRelationship,
  TemporalDataPoint,
  SourceDocument,
  ClusterDetail,
  ClusterTimelineEvent,
  PipelineStats,
  PipelineStage,
  EmbeddingStats,
  HealthStatus,
  CriticMonitoring,
  CriticExplanation,
  CriticScoreTrend,
  SnapshotDelta,
  QueryUpdate,
  LegibilityTier,
  NodeRenderState,
  QueryHistoryEntry,
  SnapshotFilters,
  ConnectionStatus,
  SourceCategory,
  FeedEntry,
  ViewMode,
  SelectedElement,
  DocumentSearchResult,
  DocumentSearchResponse,
  EntitySearchResult,
  EntitySearchResponse,
  RelationshipSearchResult,
  RelationshipSearchResponse,
  SuggestResponse,
  FacetsResponse,
} from './types'
